pipeline{
    agent any

    tools{
      maven 'Maven 3.6.1'
    }

    stages{
        stage('build'){
          when{
            changeset "**worker/**"
          }
            steps{
                echo "Building worker App..."
                dir("worker"){
                  sh 'mvn compile'
                }
            }
        }
        stage('test'){
          when{
            changeset "**worker/**"
          }
            steps{
                echo "This is Test Stage"
                dir("worker"){
                  sh 'mvn clean test'
                }
            }
        }
        stage('package'){
          when{
            changeset "**worker/**"
            branch 'master'
          }
            steps{
                echo "This is Package Stage"
                dir("worker"){
                  sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }

    post{
        always{
            echo "This is test pipeline success"
        }
    }
}
